# Generated by Django 4.1.10 on 2023-09-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_devision_code_sub_devision_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('end', models.CharField(max_length=250)),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='company.tenants')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentcategory', to='company.tenants')),
            ],
            options={
                'verbose_name': 'DocumentCategory',
                'verbose_name_plural': 'DocumentCategorys',
                'db_table': 'DocumentCategorys',
            },
        ),
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=250)),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentdetail', to='dms.document')),
            ],
            options={
                'verbose_name': 'DocumentDetail',
                'verbose_name_plural': 'DocumentDetails',
                'db_table': 'DocumentDetails',
            },
        ),
        migrations.CreateModel(
            name='DocumentDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentcategory', to='dms.documentcategory')),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentassignedment', to='dms.document')),
                ('from_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromunit', to='company.sub_devision')),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentdestination', to='company.tenants')),
                ('to_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tounit', to='company.sub_devision')),
            ],
            options={
                'verbose_name': 'DocumentDestination',
                'verbose_name_plural': 'DocumentDestinations',
                'db_table': 'DocumentDestinations',
            },
        ),
    ]
