# Generated by Django 4.1.10 on 2023-09-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_devision_code_sub_devision_code'),
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('custom_create_document', 'Can Create Document'), ('custom_delete_document', 'Can Delete Document'), ('custom_delete_change_status', 'Can Change Status of Document')], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='classification',
            field=models.CharField(blank=True, choices=[('Financial', 'Financial'), ('Application', 'Application'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todepartment', to='company.sub_devision'),
        ),
        migrations.AddField(
            model_name='document',
            name='type_of_document',
            field=models.CharField(blank=True, choices=[('Memo', 'Memo'), ('Application', 'Application'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DocumentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paragraph', models.CharField(max_length=250)),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentbudget', to='dms.document')),
            ],
            options={
                'verbose_name': 'DocumentBudget',
                'verbose_name_plural': 'DocumentBudgets',
                'db_table': 'DocumentBudgets',
            },
        ),
    ]
