# Generated by Django 4.1.10 on 2023-09-06 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0003_documentdestination_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdestination',
            name='from_unit',
        ),
        migrations.RemoveField(
            model_name='documentdestination',
            name='to_unit',
        ),
        migrations.AddField(
            model_name='document',
            name='staff_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='staff_through',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='through_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='staff_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdestination',
            name='minutes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentdestination',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Documenttimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.CharField(blank=True, max_length=255, null=True)),
                ('timeline_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenttimeline', to='dms.document')),
            ],
            options={
                'verbose_name': 'Documenttimeline',
                'verbose_name_plural': 'Documenttimelines',
                'db_table': 'Documenttimelines',
            },
        ),
    ]
