# Generated by Django 4.1.10 on 2023-09-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_documentattachement_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
