# Generated by Django 4.1.10 on 2023-09-07 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0009_documentcategory_pin_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='owner_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
