# Generated by Django 4.1.10 on 2023-09-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_documentcategory_owner_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentcategory',
            old_name='owner_to',
            new_name='owner',
        ),
    ]
