# Generated by Django 4.1.10 on 2023-09-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0011_rename_owner_to_documentcategory_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='end',
        ),
    ]
