# Generated by Django 4.1.10 on 2023-09-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0012_remove_document_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='department',
        ),
    ]
