# Generated by Django 4.1.10 on 2023-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0021_remove_documentbudget_paragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbudget',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
