# Generated by Django 4.1.10 on 2023-09-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_accountitem_maincode'),
        ('dms', '0022_documentbudget_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbudget',
            name='currency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='accounting.currency'),
        ),
    ]
