# Generated by Django 4.1.10 on 2023-09-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_accountitem_maincode'),
        ('dms', '0023_documentbudget_currency_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentbudget',
            name='currency_id',
        ),
        migrations.AddField(
            model_name='document',
            name='currency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcurrency', to='accounting.currency'),
        ),
    ]
