# Generated by Django 4.1.10 on 2023-09-12 12:21

from django.db import migrations, models
import dms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0025_rename_minutes_documentattachement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachement',
            name='attachment',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', validators=[dms.validators.validate_file_extension]),
        ),
    ]
