# Generated by Django 4.1.10 on 2023-09-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0028_documenttimeline_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdestination',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
