# Generated by Django 4.1.10 on 2023-09-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0029_documentdestination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetails',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentdestination', to='dms.documentdestination'),
        ),
        migrations.AlterField(
            model_name='documentdestination',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Wait To Send', 'Wait To Send'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
