# Generated by Django 4.1.10 on 2023-09-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0030_documentdetails_destination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('custom_create_document', 'Can Create Document'), ('custom_delete_document', 'Can Delete Document'), ('custom_delete_change_status', 'Can Change Status of Document'), ('custom_create_document_for', 'Can Create Document For'), ('custom_can_approve_document', 'Can Approve Document')], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
