# Generated by Django 4.1.10 on 2023-09-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0032_documentattachement_destination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('custom_create_document', 'Can Create Document'), ('custom_delete_document', 'Can Delete Document'), ('custom_delete_change_status', 'Can Change Status of Document'), ('custom_create_document_for', 'Can Create Document For'), ('custom_can_approve_document', 'Can Approve Document'), ('custom_can_create_pv_from_document', 'Can Create Pv From Approved Budget'), ('custom_can_add_approve_budget_amount', 'Can Add Approved Budget')], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='approved_budget',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
