# Generated by Django 4.1.10 on 2023-09-20 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0033_alter_document_options_document_approved_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttimeline',
            name='timelinedate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
