# Generated by Django 4.1.10 on 2023-09-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0034_documenttimeline_timelinedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttimeline',
            name='timelinedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
