# Generated by Django 4.1.10 on 2023-09-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0035_alter_documenttimeline_timelinedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
    ]
