# Generated by Django 4.1.10 on 2023-09-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_alter_closing_stock_closing_date_and_more'),
        ('dms', '0036_document_reverse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('custom_create_document', 'Can Create Document'), ('custom_delete_document', 'Can Delete Document'), ('custom_delete_change_status', 'Can Change Status of Document'), ('custom_create_document_for', 'Can Create Document For'), ('custom_can_approve_document', 'Can Approve Document'), ('custom_can_create_pv_from_document', 'Can Create Pv From Approved Budget'), ('custom_can_add_approve_budget_amount', 'Can Add Approved Budget'), ('custom_can_add_supplier', 'Can Add Supplier')], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='inventory.supplier'),
        ),
    ]
