# Generated by Django 4.1.10 on 2023-10-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_devision_code_sub_devision_code'),
        ('dms', '0038_document_document_from_document_document_from_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sub_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.sub_devision'),
        ),
    ]
