# Generated by Django 4.1.10 on 2023-10-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0039_document_sub_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdestination',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Wait To Send', 'Wait To Send'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Pv Created', 'Pv Created')], max_length=50, null=True),
        ),
    ]
