# Generated by Django 4.1.6 on 2024-01-31 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0042_alter_documentbeneficiary_amount_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('custom_create_document', 'Can Create Document'), ('custom_delete_document', 'Can Delete Document'), ('custom_delete_change_status', 'Can Change Status of Document'), ('custom_create_document_for', 'Can Create Document For'), ('custom_can_approve_document', 'Can Approve Document'), ('custom_can_create_pv_from_document', 'Can Create Pv From Approved Budget'), ('custom_can_add_approve_budget_amount', 'Can Add Approved Budget'), ('custom_can_add_supplier', 'Can Add Supplier'), ('custom_can_notify_procurement', 'Can Notify Procurement')], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
