# Generated by Django 4.1.6 on 2024-02-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_supplier_phone_number_supplier_supplier_email'),
        ('dms', '0043_alter_document_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentproduct', to='dms.document')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_productslist', to='inventory.products')),
            ],
            options={
                'verbose_name': 'DocumentProducts',
                'verbose_name_plural': 'DocumentProductss',
                'db_table': 'DocumentProducts',
            },
        ),
    ]
