# Generated by Django 4.1.6 on 2024-02-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0044_documentproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentproducts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
