# Generated by Django 4.1.6 on 2024-05-17 01:37

from django.db import migrations, models
import dms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0045_documentproducts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentbudget',
            name='item',
        ),
        migrations.RemoveField(
            model_name='documentbudget',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='documentbudget',
            name='total',
        ),
        migrations.AddField(
            model_name='documentbudget',
            name='attachment',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/', validators=[dms.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='documentbudget',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentbudget',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
