# Generated by Django 4.1.6 on 2024-05-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0046_remove_documentbudget_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentbeneficiary',
            name='staff',
        ),
        migrations.AddField(
            model_name='documentbeneficiary',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
