# Generated by Django 4.1.6 on 2024-05-17 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0047_remove_documentbeneficiary_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbeneficiary',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must begin with 0 and contain only 10 digits', regex='^(0)\\d{9}$')]),
        ),
    ]
