# Generated by Django 4.1.6 on 2024-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpdesk', '0002_remove_technicians_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'Teams',
                'permissions': [('custom_create_team', 'Can Create Helpdesk Team')],
            },
        ),
    ]
