# Generated by Django 4.1.6 on 2024-04-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_devision_location'),
        ('helpdesk', '0005_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='costcenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcostcenter', to='company.devision'),
        ),
        migrations.AddField(
            model_name='agent',
            name='subcostcenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentsubcostcenter', to='company.sub_devision'),
        ),
    ]
