# Generated by Django 4.1.6 on 2024-04-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_alter_agent_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'permissions': [('custom_create_agent', 'Can Create Helpdesk Agent')], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
    ]
