# Generated by Django 4.1.6 on 2024-04-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_devision_location'),
        ('helpdesk', '0009_alter_agent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'managed': True, 'permissions': [('custom_create_agent', 'Can Create Helpdesk Agent')], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('ticket_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated'), ('Closed', 'Closed')], default='Pending', max_length=50, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50, null=True)),
                ('costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketcostcenter', to='company.devision')),
                ('subcostcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketsubcostcenter', to='company.sub_devision')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'Tickets',
                'permissions': [('custom_create_ticket', 'Can Create Ticket'), ('custom_solve_ticket', 'Can solve ticket'), ('custom_helpdesk', 'Can Be Helpdesk')],
                'managed': True,
            },
        ),
    ]
