# Generated by Django 4.1.6 on 2024-04-14 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0010_alter_agent_options_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
