# Generated by Django 4.1.6 on 2024-04-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_ticket_ticketuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated'), ('Closed', 'Closed')], max_length=50, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50, null=True)),
                ('assigneddate', models.DateField()),
                ('completeddate', models.DateField()),
                ('assignedtime', models.TimeField()),
                ('completedtime', models.TimeField()),
                ('timetaken', models.DateField()),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdeskagent', to='helpdesk.agent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentticket', to='helpdesk.ticket')),
            ],
            options={
                'verbose_name': 'AgentTicket',
                'verbose_name_plural': 'AgentTickets',
                'db_table': 'AgentTicket',
                'managed': True,
            },
        ),
    ]
