# Generated by Django 4.1.6 on 2024-04-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_agentticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentticket',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignlevel', to='helpdesk.level'),
        ),
        migrations.AlterField(
            model_name='agentticket',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpdeskagent', to='helpdesk.agent'),
        ),
        migrations.AlterField(
            model_name='agentticket',
            name='assigneddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentticket',
            name='assignedtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentticket',
            name='completeddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentticket',
            name='completedtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentticket',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentticket', to='helpdesk.ticket'),
        ),
        migrations.AlterField(
            model_name='agentticket',
            name='timetaken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
