# Generated by Django 4.1.6 on 2024-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_agentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentticket',
            name='completed_days',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentticket',
            name='elapsed_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
