# Generated by Django 4.1.6 on 2024-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_agentticket_expected_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentticket',
            name='assigneddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentticket',
            name='completeddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
