# Generated by Django 4.1.6 on 2024-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_alter_agentticket_assigneddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentticket',
            name='use_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
