# Generated by Django 4.1.6 on 2024-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0020_alter_agentticket_assigneddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completeddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='expecteddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
