# Generated by Django 4.1.6 on 2024-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0021_ticket_completeddate_ticket_expecteddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_days',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentticket',
            name='expected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
