# Generated by Django 4.1.6 on 2024-04-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0022_ticket_completed_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigndate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
