# Generated by Django 4.1.6 on 2023-12-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annual_Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=250, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('amount_spent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('amount_left', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Annual_Budget',
                'verbose_name_plural': 'Annual_Budgets',
                'db_table': 'Annual_Budget',
                'permissions': [('custom_create_budget', 'Can Create Budget'), ('custom_approve_budget', 'Can Approve Budget'), ('custom_cancel_budget', 'Can Cancel Budget')],
            },
        ),
    ]
