# Generated by Django 4.1.6 on 2023-12-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annual_budget',
            options={'permissions': [('custom_create_budget', 'Can Create Budget'), ('custom_approve_budget', 'Can Approve Budget'), ('custom_cancel_budget', 'Can Cancel Budget'), ('custom_view_budget', 'Can View Budget')], 'verbose_name': 'Annual_Budget', 'verbose_name_plural': 'Annual_Budgets'},
        ),
    ]
