# Generated by Django 4.1.6 on 2024-01-31 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0062_supplier_phone_number_supplier_supplier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('purchase_requisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PurchaseRequisition',
                'verbose_name_plural': 'PurchaseRequisitions',
                'db_table': 'PurchaseRequisition',
                'permissions': [('custom_create_purchase_requisition', 'Can Create PurchaseRequisition'), ('custom_update_purchase_requisition', 'Can Update PurchaseRequisition'), ('custom_delete_purchase_requisition', 'Can Delete PurchaseRequisition'), ('custom_view_purchase_requisition', 'Can View PurchaseRequisition'), ('custom_approve_purchase_requisition', 'Can Approve PurchaseRequisition')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Issued', 'Issued')], default='Pending', max_length=50, null=True)),
                ('release', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaserequisition_products', to='inventory.products')),
                ('purchase_requisition_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitems', to='purchase_order.purchaserequisition')),
            ],
            options={
                'verbose_name': 'PurchaseRequisition_Detail',
                'verbose_name_plural': 'PurchaseRequisition_Details',
                'db_table': 'PurchaseRequisition_Details',
            },
        ),
    ]
