# Generated by Django 4.1.6 on 2024-02-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_supplier_phone_number_supplier_supplier_email'),
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaserequisition_products', to='inventory.products'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseRequisition_Details',
        ),
    ]
