# Generated by Django 4.1.6 on 2024-02-01 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_supplier_phone_number_supplier_supplier_email'),
        ('purchase_order', '0002_purchaserequisition_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition_Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=20, null=True)),
                ('purchase_requisition_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitems', to='purchase_order.purchaserequisition')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_suppliers', to='inventory.products')),
            ],
            options={
                'verbose_name': 'PurchaseRequisition_Supplier',
                'verbose_name_plural': 'PurchaseRequisition_Supplier',
                'db_table': 'PurchaseRequisition_Supplier',
            },
        ),
    ]
