# Generated by Django 4.1.6 on 2024-02-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_supplier_phone_number_supplier_supplier_email'),
        ('purchase_order', '0003_purchaserequisition_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition_suppliers',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_suppliers', to='inventory.supplier'),
        ),
    ]
