# Generated by Django 4.1.6 on 2024-02-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_rename_suppliers_product_supplier_products'),
        ('purchase_order', '0005_alter_purchaserequisition_suppliers_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_supplier', to='inventory.supplier'),
        ),
    ]
