# Generated by Django 4.1.6 on 2024-02-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_purchaserequisition_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('LPO Created', 'LPO Created')], default='Pending', max_length=20, null=True),
        ),
    ]
