# Generated by Django 4.1.6 on 2024-02-01 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_rename_suppliers_product_supplier_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_order', '0007_alter_purchaserequisition_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPurchasingOrder',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('purchase_requisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lpon_products', to='inventory.products')),
                ('purchase_requisition_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lpopurchaserequisition', to='purchase_order.purchaserequisition')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lpo_supplier', to='inventory.supplier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LocalPurchasingOrder',
                'verbose_name_plural': 'LocalPurchasingOrders',
                'db_table': 'LocalPurchasingOrdern',
                'permissions': [('custom_create_lpo', 'Can Create LPO'), ('custom_update_lpo', 'Can Update LPO'), ('custom_delete_lpo', 'Can Delete LPO'), ('custom_view_lpo', 'Can View LPO'), ('custom_approve_lpo', 'Can Approve LPO')],
            },
        ),
    ]
