# Generated by Django 4.1.6 on 2024-02-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0008_localpurchasingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='release',
            field=models.BooleanField(default=False),
        ),
    ]
