# Generated by Django 4.1.6 on 2024-02-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0010_alter_localpurchasingorder_purchase_requisition_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localpurchasingorder',
            old_name='purchase_requisition_date',
            new_name='lpo_date',
        ),
    ]
