# Generated by Django 4.1.10 on 2023-07-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appmodules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Systemconfig',
                'verbose_name_plural': 'Systemconfigs',
                'db_table': 'Systemconfig',
            },
        ),
    ]
