# Generated by Django 4.1.10 on 2023-07-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('appsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmodules',
            name='status',
        ),
        migrations.CreateModel(
            name='Companymodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyapp', to='company.tenants')),
            ],
        ),
    ]
