# Generated by Django 4.1.10 on 2023-07-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsystem', '0002_remove_appmodules_status_companymodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodule',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app', to='appsystem.appmodules'),
        ),
    ]
