# Generated by Django 4.1.6 on 2024-05-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsystem', '0003_companymodule_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmodules',
            options={'permissions': [('custom_access_to_inventory', 'Have Access To Inventory'), ('custom_access_to_accounting', 'Have Access To Accounting'), ('custom_access_to_dms', 'Have Access To DMS'), ('custom_access_to_helpdesk', 'Have Access To Helpdesk'), ('custom_access_to_fixedasset', 'Have Access To Fixed Asset'), ('custom_access_to_pensions', 'Have Access To Pensions')], 'verbose_name': 'Systemconfig', 'verbose_name_plural': 'Systemconfigs'},
        ),
    ]
