# Generated by Django 4.1.6 on 2024-03-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingrecognition',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognitionclassification', to='fixedassets.classification'),
        ),
        migrations.AddField(
            model_name='historicalaccountingrecognition',
            name='classification',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fixedassets.classification'),
        ),
    ]
