# Generated by Django 4.1.6 on 2024-03-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0002_accountingrecognition_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalipsascategory',
            name='gfscategory',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ipsascategory',
            name='gfscategory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
