# Generated by Django 4.1.6 on 2024-03-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0004_gfscategory_historicalgfscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfscategory',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalgfscategory',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
