# Generated by Django 4.1.6 on 2024-03-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0005_gfscategory_code_historicalgfscategory_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalipsascategory',
            name='gfscategory',
        ),
        migrations.RemoveField(
            model_name='ipsascategory',
            name='gfscategory',
        ),
    ]
