# Generated by Django 4.1.6 on 2024-03-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0010_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='usefullife',
            new_name='usefullifes',
        ),
    ]
