# Generated by Django 4.1.6 on 2024-03-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_sub_devision_tag'),
        ('inventory', '0069_remove_job_certification_lpo_id_and_more'),
        ('authentication', '0026_alter_historicalgrade_options_and_more'),
        ('fixedassets', '0012_rename_usefullifes_asset_usefullife'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='FixedAsset',
        ),
        migrations.AlterModelOptions(
            name='fixedasset',
            options={'permissions': [('custom_create_fixedassets', 'Can Create Fixed Assets'), ('custom_view_fixedassets', 'Can View Fixed Assets'), ('custom_delete_fixedassets', 'Can Delete Fixed Assets'), ('custom_run_depreciation_on_fixed', 'Can Run Depreciaition on Fixed Assets')], 'verbose_name': 'FixedAsset', 'verbose_name_plural': 'FixedAssets'},
        ),
        migrations.AlterModelTable(
            name='fixedasset',
            table='FixedAssets',
        ),
    ]
