# Generated by Django 4.1.6 on 2024-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0013_rename_asset_fixedasset_alter_fixedasset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='accumulateddepreciation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Needs Repair/Renovation/Servicing', 'Needs Repair/Renovation/Servicing'), ('Irrepairable/Unserviceable', 'Irrepairable/Unserviceable'), ('Not Sighted', 'Not Sighted')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='dateplacedinservice',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='depreciation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='netbookvalue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='totaldepreciation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='usagetype',
            field=models.CharField(choices=[('Pool', 'Pool'), ('Assigned', 'Assigned')], max_length=10, null=True),
        ),
    ]
