# Generated by Django 4.1.6 on 2024-03-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0014_fixedasset_accumulateddepreciation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedasset',
            old_name='condition',
            new_name='conditions',
        ),
    ]
