# Generated by Django 4.1.6 on 2024-03-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_remove_job_certification_lpo_id_and_more'),
        ('fixedassets', '0016_fixedasset_registrationnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='chassisno',
            field=models.CharField(error_messages={'unique': 'Vehicle With this Chassis number already exist.'}, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='colour',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='engineserialno',
            field=models.CharField(error_messages={'unique': 'Vehicle With this Engine number already exist.'}, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturername', to='inventory.brands'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='modelyear',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
