# Generated by Django 4.1.6 on 2024-03-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0018_alter_fixedasset_modelyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubcategory',
            name='ipsascategory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fixedassets.ipsascategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='ipsascategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryipsas', to='fixedassets.ipsascategory'),
        ),
    ]
