# Generated by Django 4.1.6 on 2024-03-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0019_historicalsubcategory_ipsascategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='fixedassets.subcategory'),
        ),
    ]
