# Generated by Django 4.1.6 on 2024-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0022_fixedasset_tagno_alter_fixedasset_chassisno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='accountingstatus',
            field=models.CharField(choices=[('In-progress', 'In-progress'), ('Completed', 'Completed'), ('Completed and Transferred', 'Completed and Transferred')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='commencement_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='expectedcompletion_date',
            field=models.DateField(null=True),
        ),
    ]
