# Generated by Django 4.1.6 on 2024-03-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0023_fixedasset_accountingstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='costbf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='costcf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='currentperiodcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='currentstatus',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Not in Use', 'Not in Use'), ('Retired', 'Retired'), ('Disposed', 'Disposed'), ('On-going', 'On-going'), ('Abandoned', 'Abandoned'), ('Suspended', 'Suspended')], max_length=30, null=True),
        ),
    ]
