# Generated by Django 4.1.6 on 2024-03-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0026_fixedassetsassignment_usagetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedassetsassignment',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Assigned', 'Assigned')], default='Assigned', max_length=50, null=True),
        ),
    ]
