# Generated by Django 4.1.6 on 2024-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0027_fixedassetsassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Avialable', 'Avialable')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='currentstatus',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Not in Use', 'Not in Use'), ('Retired', 'Retired'), ('Disposed', 'Disposed'), ('On-going', 'On-going'), ('Abandoned', 'Abandoned'), ('Suspended', 'Suspended')], max_length=30, null=True),
        ),
    ]
