# Generated by Django 4.1.6 on 2024-03-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_alter_imprest_amount'),
        ('fixedassets', '0029_alter_fixedasset_currentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depreciationvalue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('accountingyear', models.OneToOneField(error_messages={'unique': 'Depreciation For This Accounting Year Has Already Been Calculated.'}, on_delete=django.db.models.deletion.CASCADE, related_name='accountingyear', to='accounting.fiscal_year')),
            ],
            options={
                'verbose_name': 'Depreciation',
                'verbose_name_plural': 'Depreciations',
                'db_table': 'Depreciations',
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='depreciatedlife',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='usefullifebalance',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='DepreciationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depreciationvalue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depreciationasset', to='fixedassets.fixedasset')),
                ('depreciation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depreciationdetail', to='fixedassets.depreciation')),
            ],
            options={
                'verbose_name': 'DepreciationDetail',
                'verbose_name_plural': 'DepreciationDetails',
                'db_table': 'DepreciationDetails',
                'managed': True,
            },
        ),
    ]
