# Generated by Django 4.1.6 on 2024-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0030_depreciation_fixedasset_depreciatedlife_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciation',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=50, null=True),
        ),
    ]
