# Generated by Django 4.1.6 on 2024-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0032_alter_fixedasset_accumulateddepreciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='currentdepreciation',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
