# Generated by Django 4.1.6 on 2024-03-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0033_fixedasset_currentdepreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciation',
            name='depreciationvalue',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
