# Generated by Django 4.1.6 on 2024-03-25 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_alter_imprest_amount'),
        ('fixedassets', '0035_alter_depreciation_depreciationvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldvalue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('newvalue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('previoususefullife', models.PositiveIntegerField(default=0, null=True)),
                ('usefullife', models.PositiveIntegerField(default=0, null=True)),
                ('accountingyear', models.OneToOneField(error_messages={'unique': 'Depreciation For This Accounting Year Has Already Been Calculated.'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluateaccountingyear', to='accounting.fiscal_year')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluationasset', to='fixedassets.fixedasset')),
            ],
            options={
                'verbose_name': 'Reevaluation',
                'verbose_name_plural': 'Reevaluations',
                'db_table': 'Reevaluations',
            },
        ),
    ]
