# Generated by Django 4.1.6 on 2024-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0039_disposals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposals',
            name='proceedsfromsales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
