# Generated by Django 4.1.6 on 2024-04-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0071_remove_job_detail_brand_id_remove_job_detail_funding_and_more'),
        ('fixedassets', '0040_alter_disposals_proceedsfromsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedassetsassignment',
            name='requisition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignrequisition', to='inventory.requisition'),
        ),
    ]
