# Generated by Django 4.1.6 on 2024-04-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_remove_job_certification_driver_contact_and_more'),
        ('fixedassets', '0041_fixedassetsassignment_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedassetsassignment',
            name='allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignallocation', to='inventory.allocation'),
        ),
    ]
