# Generated by Django 4.1.6 on 2024-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0042_fixedassetsassignment_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='sra',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
