# Generated by Django 4.1.10 on 2023-07-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'permissions': [('custom_create_brand', 'Can Create Brand'), ('custom_update_brand', 'Can Update Brand'), ('custom_delete_brand', 'Can Delete Brand'), ('custom_view_brand', 'Can View Brand')], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='categorys',
            options={'permissions': [('custom_create_category', 'Can Create Category'), ('custom_update_category', 'Can Update Category'), ('custom_delete_category', 'Can Delete Category'), ('custom_view_measuremnt', 'Can View Category')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='unit_of_measurement',
            options={'permissions': [('custom_create_measuremnt', 'Can Create Measurement'), ('custom_update_measuremnt', 'Can Update Measurement'), ('custom_delete_measuremnt', 'Can Delete Measurement'), ('custom_view_measuremnt', 'Can View Measurement')], 'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
    ]
