# Generated by Django 4.1.10 on 2023-07-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_brands_options_alter_categorys_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorys',
            options={'permissions': [('custom_create_category', 'Can Create Category'), ('custom_update_category', 'Can Update Category'), ('custom_delete_category', 'Can Delete Category'), ('custom_view_category', 'Can View Category')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
