# Generated by Django 4.1.10 on 2023-07-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_categorys_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'permissions': [('custom_create_brand', 'Can Create Brand')], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='categorys',
            options={'permissions': [('custom_create_category', 'Can Create Category')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='unit_of_measurement',
            options={'permissions': [('custom_create_measuremnt', 'Can Create Measurement')], 'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
    ]
