# Generated by Django 4.1.10 on 2023-07-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_inventory_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category_id',
        ),
    ]
