# Generated by Django 4.1.10 on 2023-07-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0008_remove_inventory_details_brand_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_inventory', to='company.tenants'),
        ),
        migrations.AddField(
            model_name='products',
            name='type_of_product',
            field=models.CharField(blank=True, choices=[('Capital', 'Capital'), ('Consumable', 'Consumable')], max_length=50, null=True),
        ),
    ]
