# Generated by Django 4.1.10 on 2023-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory_tenant_id_products_type_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type_of_product',
            field=models.CharField(blank=True, choices=[('Capital', 'Capital'), ('Consumables', 'Consumables')], max_length=50, null=True),
        ),
    ]
