# Generated by Django 4.1.10 on 2023-07-24 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0011_brands_tenant_id_categorys_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock_date', models.DateTimeField()),
                ('driver_name', models.CharField(blank=True, max_length=250, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must begin with 0 and contain only 10 digits', regex='^(0)\\d{9}$')])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restock', to='company.tenants')),
            ],
        ),
        migrations.CreateModel(
            name='Restock_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('expiring_date', models.DateField(null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
        ),
    ]
