# Generated by Django 4.1.10 on 2023-07-25 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0014_alter_restock_details_options_alter_restocks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restock_details',
            options={'verbose_name': 'Restock_detail', 'verbose_name_plural': 'Restock_details'},
        ),
        migrations.AddField(
            model_name='restocks',
            name='classification',
            field=models.CharField(blank=True, choices=[('Capital', 'Capital'), ('Consumables', 'Consumables')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restocks',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restock', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='Job_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=250, null=True)),
                ('expiring_date', models.DateField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
            options={
                'verbose_name': 'Job_detail',
                'verbose_name_plural': 'Job_details',
                'db_table': 'Job_detail',
            },
        ),
        migrations.CreateModel(
            name='Job_Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateTimeField()),
                ('driver_name', models.CharField(blank=True, max_length=250, null=True)),
                ('describtion', models.CharField(max_length=250)),
                ('driver_contact', models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must begin with 0 and contain only 10 digits', regex='^(0)\\d{9}$')])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('classification', models.CharField(blank=True, choices=[('Capital', 'Capital'), ('Consumables', 'Consumables')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcert', to='inventory.supplier')),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='company.tenants')),
            ],
            options={
                'verbose_name': 'JobCertification',
                'verbose_name_plural': 'JobCertifications',
                'db_table': 'JobCertification',
            },
        ),
    ]
