# Generated by Django 4.1.10 on 2023-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_restock_details_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock_details',
            name='batch_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
