# Generated by Django 4.1.10 on 2023-07-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_restock_details_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock_details',
            name='batch_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
