# Generated by Django 4.1.10 on 2023-07-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_restocks_classification'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restock_details',
            table='Restock_details',
        ),
    ]
