# Generated by Django 4.1.10 on 2023-07-26 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0021_remove_job_certification_classification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_certification',
            options={'permissions': [('custom_create_job_certification', 'Can Create Job Certification'), ('custom_update_job_certification', 'Can Update Job Certification'), ('custom_delete_job_certification', 'Can Delete Job Certification'), ('custom_view_job_certification', 'Can View Job Certification')], 'verbose_name': 'JobCertification', 'verbose_name_plural': 'JobCertifications'},
        ),
        migrations.RemoveField(
            model_name='job_certification',
            name='describtion',
        ),
        migrations.RemoveField(
            model_name='job_certification',
            name='product_id',
        ),
        migrations.CreateModel(
            name='Assigned_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=250, null=True)),
                ('describtion', models.CharField(blank=True, max_length=250, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Assigned',
                'verbose_name_plural': 'User_Assigneds',
                'db_table': 'User_Assigned',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=250, null=True)),
                ('describtion', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'Asset',
            },
        ),
    ]
