# Generated by Django 4.1.10 on 2023-07-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_job_certification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_certification',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_certification',
            name='quantity_accepted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_certification',
            name='quantity_rejected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
