# Generated by Django 4.1.10 on 2023-07-26 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_job_detail_expiring_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_detail',
            name='restock_id',
        ),
        migrations.AddField(
            model_name='job_detail',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.job_certification'),
        ),
    ]
