# Generated by Django 4.1.10 on 2023-07-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_remove_job_detail_restock_id_job_detail_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='funding',
            field=models.CharField(choices=[('Gov. of Ghana', 'Gov. of Ghana'), ('Donor', 'Donor')], default='Gov. of Ghana', max_length=100),
        ),
    ]
