# Generated by Django 4.1.10 on 2023-07-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_job_detail_funding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_detail',
            old_name='describtion',
            new_name='description',
        ),
    ]
