# Generated by Django 4.1.10 on 2023-07-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_assets_tenant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigned_assets',
            old_name='describtion',
            new_name='description',
        ),
    ]
