# Generated by Django 4.1.10 on 2023-07-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_rename_describtion_assigned_assets_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='describtion',
            new_name='description',
        ),
    ]
