# Generated by Django 4.1.10 on 2023-07-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_rename_describtion_assets_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brands'),
        ),
        migrations.AddField(
            model_name='assigned_assets',
            name='assets_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.assets'),
        ),
    ]
