# Generated by Django 4.1.10 on 2023-07-26 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0033_assets_brand_id_assigned_assets_assets_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Awaiting Approval', 'Awaiting Approval'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('classification', models.CharField(blank=True, choices=[('Capital', 'Capital'), ('Consumables', 'Consumables')], max_length=60, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisition',
                'verbose_name_plural': 'Requisitions',
                'db_table': 'Requisition',
                'permissions': [('custom_create_job_certification', 'Can Create Job Certification'), ('custom_update_job_certification', 'Can Update Job Certification'), ('custom_delete_job_certification', 'Can Delete Job Certification'), ('custom_view_job_certification', 'Can View Job Certification')],
            },
        ),
        migrations.CreateModel(
            name='Requisition_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_date', models.DateField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_approved', models.IntegerField(default=0)),
                ('quantity_issued', models.IntegerField(default=0)),
                ('remender', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('release', models.BooleanField(default=False)),
                ('approval', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Authorized', 'Authorized'), ('Admin Cancelled', 'Admin Cancelled'), ('Issued', 'Issued')], default='Pending', max_length=30, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('requisition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.requisition')),
            ],
            options={
                'verbose_name': 'Requisition_Detail',
                'verbose_name_plural': 'Requisition_Details',
                'db_table': 'Requisition_Detail',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRequisition_Details',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('detail_date', models.DateField(blank=True, editable=False, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_approved', models.IntegerField(default=0)),
                ('quantity_issued', models.IntegerField(default=0)),
                ('remender', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('release', models.BooleanField(default=False)),
                ('approval', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Authorized', 'Authorized'), ('Admin Cancelled', 'Admin Cancelled'), ('Issued', 'Issued')], default='Pending', max_length=30, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.products')),
                ('requisition_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.requisition')),
            ],
            options={
                'verbose_name': 'historical Requisition_Detail',
                'verbose_name_plural': 'historical Requisition_Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRequisition',
            fields=[
                ('id', models.CharField(db_index=True, max_length=2000)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Awaiting Approval', 'Awaiting Approval'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('classification', models.CharField(blank=True, choices=[('Capital', 'Capital'), ('Consumables', 'Consumables')], max_length=60, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Requisition',
                'verbose_name_plural': 'historical Requisitions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
