# Generated by Django 4.1.10 on 2023-07-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_requisition_requisition_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'permissions': [('custom_create_requisition', 'Can Create Requisition'), ('custom_update_requisition', 'Can Update Requisition'), ('custom_delete_requisition', 'Can Delete Requisition'), ('custom_view_requisition', 'Can View Requisition')], 'verbose_name': 'Requisition', 'verbose_name_plural': 'Requisitions'},
        ),
    ]
