# Generated by Django 4.1.10 on 2023-07-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_historicalrequisition_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequisition_details',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Authorized', 'Authorized'), ('Admin Cancelled', 'Admin Cancelled'), ('Issued', 'Issued')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisition_details',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Authorized', 'Authorized'), ('Admin Cancelled', 'Admin Cancelled'), ('Issued', 'Issued')], default='Pending', max_length=50, null=True),
        ),
    ]
