# Generated by Django 4.1.10 on 2023-07-31 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_historicalrequisition_release_requisition_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_assets',
            name='requisition_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.requisition'),
        ),
    ]
