# Generated by Django 4.1.10 on 2023-07-31 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_approvals'),
        ('inventory', '0045_assigned_assets_requisition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_assets',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='company.tenants'),
        ),
    ]
