# Generated by Django 4.1.10 on 2023-08-02 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0048_historicalrequisition_devision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('release', models.BooleanField(default=False)),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationtenant', to='company.tenants')),
            ],
            options={
                'verbose_name': 'Allocation',
                'verbose_name_plural': 'Allocations',
                'db_table': 'Allocation',
                'permissions': [('custom_create_allocation', 'Can Create Allocation'), ('custom_update_allocation', 'Can Update Allocation'), ('custom_delete_allocation', 'Can Delete Allocation'), ('custom_view_allocation', 'Can View Allocation')],
            },
        ),
        migrations.CreateModel(
            name='Allocation_Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.BooleanField(default=False)),
                ('allocation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.allocation')),
                ('devision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocdevisions', to='company.devision')),
                ('sub_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocsub_districts', to='company.sub_devision')),
            ],
            options={
                'verbose_name': 'Allocation_Destination',
                'verbose_name_plural': 'Allocation_Destinations',
                'db_table': 'Allocation_Destination',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAllocation_Details',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('detail_date', models.DateField(blank=True, editable=False, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_issued', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Authorized', 'Authorized'), ('Admin Cancelled', 'Admin Cancelled'), ('Issued', 'Issued')], default='Pending', max_length=50, null=True)),
                ('release', models.BooleanField(default=False)),
                ('approval', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Authorized', 'Authorized'), ('Admin Cancelled', 'Admin Cancelled'), ('Issued', 'Issued')], default='Pending', max_length=30, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('destination_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.allocation_destination')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.products')),
            ],
            options={
                'verbose_name': 'historical Allocation_Detail',
                'verbose_name_plural': 'historical Allocation_Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAllocation_Destination',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('release', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('allocation_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.allocation')),
                ('devision', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.devision')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sub_division', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.sub_devision')),
            ],
            options={
                'verbose_name': 'historical Allocation_Destination',
                'verbose_name_plural': 'historical Allocation_Destinations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAllocation',
            fields=[
                ('id', models.CharField(db_index=True, max_length=2000)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('release', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.tenants')),
            ],
            options={
                'verbose_name': 'historical Allocation',
                'verbose_name_plural': 'historical Allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Allocation_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_date', models.DateField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_issued', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Authorized', 'Authorized'), ('Admin Cancelled', 'Admin Cancelled'), ('Issued', 'Issued')], default='Pending', max_length=50, null=True)),
                ('release', models.BooleanField(default=False)),
                ('approval', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Authorized', 'Authorized'), ('Admin Cancelled', 'Admin Cancelled'), ('Issued', 'Issued')], default='Pending', max_length=30, null=True)),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.allocation_destination')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
            options={
                'verbose_name': 'Allocation_Detail',
                'verbose_name_plural': 'Allocation_Details',
                'db_table': 'Allocation_Detail',
            },
        ),
    ]
