# Generated by Django 4.1.10 on 2023-08-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_allocation_devision_historicalallocation_devision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_destination',
            name='release',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalallocation_destination',
            name='release',
            field=models.BooleanField(default=True),
        ),
    ]
