# Generated by Django 4.1.10 on 2023-08-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_alter_allocation_destination_release_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation_destination',
            name='classification',
            field=models.CharField(blank=True, choices=[('Capital', 'Capital'), ('Consumables', 'Consumables')], default='Consumables', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation_destination',
            name='classification',
            field=models.CharField(blank=True, choices=[('Capital', 'Capital'), ('Consumables', 'Consumables')], default='Consumables', max_length=60, null=True),
        ),
    ]
