# Generated by Django 4.1.10 on 2023-08-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_alter_allocation_destination_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation_destination',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assigned_assets',
            name='allocation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.allocation_destination'),
        ),
        migrations.AddField(
            model_name='historicalallocation_destination',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
