# Generated by Django 4.1.10 on 2023-08-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_historicalclosing_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closing_stock_inventory',
            options={'verbose_name': 'Closing-Stock-Inventory', 'verbose_name_plural': 'Closing-Stock-Inventorys'},
        ),
        migrations.AlterModelOptions(
            name='closing_stock_inventory_details',
            options={'verbose_name': 'Closing-Stock-Inventory-Detail', 'verbose_name_plural': 'Closing-Stock-Inventory-Details'},
        ),
        migrations.RemoveField(
            model_name='closing_stock_inventory_details',
            name='closing_id',
        ),
        migrations.AddField(
            model_name='closing_stock_inventory',
            name='closing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing', to='inventory.closing_stock'),
        ),
        migrations.AddField(
            model_name='closing_stock_inventory_details',
            name='closing_inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_inventory_details', to='inventory.closing_stock_inventory'),
        ),
        migrations.AlterModelTable(
            name='closing_stock_inventory',
            table='Closing-Stock-Inventory',
        ),
        migrations.AlterModelTable(
            name='closing_stock_inventory_details',
            table='Closing-Stock-Inventory-Detail',
        ),
    ]
