# Generated by Django 4.1.10 on 2023-08-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_alter_closing_stock_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing_stock',
            name='closing_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclosing_stock',
            name='closing_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
