# Generated by Django 4.1.10 on 2023-08-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_alter_closing_stock_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing_stock',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclosing_stock',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
