# Generated by Django 4.1.6 on 2023-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_alter_closing_stock_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalallocation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Allocation'},
        ),
        migrations.AlterModelOptions(
            name='historicalallocation_destination',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Allocation_Destination'},
        ),
        migrations.AlterModelOptions(
            name='historicalallocation_details',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Allocation_Detail'},
        ),
        migrations.AlterModelOptions(
            name='historicalclosing_stock',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Closing-Stock'},
        ),
        migrations.AlterModelOptions(
            name='historicalrequisition',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Requisition'},
        ),
        migrations.AlterModelOptions(
            name='historicalrequisition_details',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Requisition_Detail'},
        ),
        migrations.AlterField(
            model_name='historicalallocation',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalallocation_destination',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalallocation_details',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalclosing_stock',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalrequisition',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalrequisition_details',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
