# Generated by Django 4.1.6 on 2024-01-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_alter_historicalallocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_product', to='inventory.products')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Suppliers_Product',
                'verbose_name_plural': 'Suppliers_Products',
                'db_table': 'Suppliers_Product',
            },
        ),
    ]
