# Generated by Django 4.1.6 on 2024-01-31 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_supplier_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must begin with 0 and contain only 10 digits', regex='^(0)\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
