# Generated by Django 4.1.6 on 2024-02-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_supplier_phone_number_supplier_supplier_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier_Products',
            new_name='Suppliers_Product',
        ),
    ]
