# Generated by Django 4.1.6 on 2024-02-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_rename_supplier_products_suppliers_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suppliers_Product',
            new_name='Supplier_Products',
        ),
    ]
