# Generated by Django 4.1.6 on 2024-02-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_rename_suppliers_product_supplier_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='funding',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Donor', 'Donor')], default='Internal', max_length=100),
        ),
    ]
