# Generated by Django 4.1.6 on 2024-02-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_job_certification_lpo_id_restocks_lpo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_certification',
            name='note',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
