# Generated by Django 4.1.6 on 2024-02-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_job_certification_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='restocks',
            name='note',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
