# Generated by Django 4.1.6 on 2024-02-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_restocks_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_certification',
            name='lpo_id',
        ),
        migrations.RemoveField(
            model_name='restocks',
            name='lpo_id',
        ),
    ]
