# Generated by Django 4.1.6 on 2024-04-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0040_alter_disposals_proceedsfromsales'),
        ('inventory', '0069_remove_job_certification_lpo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_certification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcategory', to='inventory.categorys'),
        ),
        migrations.AddField(
            model_name='job_certification',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobclassification', to='fixedassets.classification'),
        ),
        migrations.AddField(
            model_name='job_certification',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_certification',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobproduct', to='inventory.products'),
        ),
    ]
