# Generated by Django 4.1.6 on 2024-04-01 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixedassets', '0040_alter_disposals_proceedsfromsales'),
        ('authentication', '0026_alter_historicalgrade_options_and_more'),
        ('company', '0008_remove_devision_location'),
        ('inventory', '0070_job_certification_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_detail',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='funding',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='job_detail',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='job_detail',
            name='accountingrecognition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobaccountingrecognition', to='fixedassets.accountingrecognition'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='accountingstatus',
            field=models.CharField(choices=[('In-progress', 'In-progress'), ('Completed', 'Completed'), ('Completed and Transferred', 'Completed and Transferred')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='accumulateddepreciation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='amotization',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='chassisno',
            field=models.CharField(error_messages={'unique': 'Asset With this Chassis/Serial number already exist.'}, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='colour',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='commencement_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='conditions',
            field=models.CharField(choices=[('Good', 'Good'), ('Needs Repair/Renovation/Servicing', 'Needs Repair/Renovation/Servicing'), ('Irrepairable/Unserviceable', 'Irrepairable/Unserviceable'), ('Not Sighted', 'Not Sighted')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='costbf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='costcenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobassetcostcenter', to='company.devision'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='costcf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='currentdepreciation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='currentperiodcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='dateplacedinservice',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='depreciatedlife',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='depreciation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='desposal_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='engineserialno',
            field=models.CharField(error_messages={'unique': 'Asset With this Tag number already exist.'}, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='expectedcompletion_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='fundsource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobassetfundsource', to='fixedassets.sourceoffunding'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='gfscategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobgfscategory', to='fixedassets.gfscategory'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='ghanapostgpsaddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='investmentproperty',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='ipsascategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobipsascategory', to='fixedassets.ipsascategory'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobassetlocation', to='fixedassets.location'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmanufacturername', to='inventory.brands'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='methodofacquisition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobassetmethodofacquisition', to='fixedassets.mothodofacquisition'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='methodofdesposal',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Auction', 'Auction'), ('Donated', 'Donated'), ('Trade-in/Exchanged', 'Trade-in/Exchanged'), ('Transfer-out to Other Govt Entities', 'Transfer-out to Other Govt Entities'), ('Scrapped', 'Scrapped')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='modelyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='netbookvalue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobposition', to='authentication.grade'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='proceedsfromsales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobfixedassetproduct', to='inventory.products'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='registrationnumber',
            field=models.CharField(error_messages={'unique': 'Vehicle With this Registration number already exist.'}, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='staffid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobsubcategory', to='fixedassets.subcategory'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='subcostcenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobassetsubcostcenter', to='company.sub_devision'),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='tagno',
            field=models.CharField(error_messages={'unique': 'Asset With this Chassis/Serial number already exist.'}, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='titled',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='totaldepreciation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='usage',
            field=models.CharField(choices=[('Public Domain', 'Public Domain'), ('Private Domain', 'Private Domain')], max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='usagetype',
            field=models.CharField(choices=[('Pool', 'Pool'), ('Assigned', 'Assigned')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='usefullife',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='usefullifebalance',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcurrentuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
