# Generated by Django 4.1.6 on 2024-04-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_remove_job_certification_driver_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing_stock',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclosing_stock',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
