# Generated by Django 4.1.6 on 2024-05-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_alter_closing_stock_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_certification',
            name='sra',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
