# Generated by Django 4.1.10 on 2023-07-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_custompermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('custom_create_user', 'Can Create User'), ('custom_delete_user', 'Can Delete User'), ('custom_update_user', 'Can Update User'), ('custom_view_user', 'Can View User')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
