# Generated by Django 4.1.10 on 2023-07-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_grade_region_historicaluser_historicalregion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='districtname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicaldistrict',
            old_name='districtname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicalregion',
            old_name='region_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_name',
            new_name='name',
        ),
    ]
