# Generated by Django 4.1.10 on 2023-07-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_districtname_district_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'permissions': [('custom_create_district', 'Can Create District'), ('custom_delete_district', 'Can Delete District'), ('custom_update_district', 'Can Update District'), ('custom_view_district', 'Can View District')], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'permissions': [('custom_create_rank', 'Can Create Rank'), ('custom_delete_rank', 'Can Delete Rank'), ('custom_update_rank', 'Can Update Rank'), ('custom_view_Rank', 'Can View Rank')], 'verbose_name': 'Rank', 'verbose_name_plural': 'Ranks'},
        ),
        migrations.AlterModelOptions(
            name='historicaldistrict',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical District', 'verbose_name_plural': 'historical Districts'},
        ),
        migrations.AlterModelOptions(
            name='historicalgrade',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Rank', 'verbose_name_plural': 'historical Ranks'},
        ),
        migrations.AlterModelOptions(
            name='historicalregion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Region', 'verbose_name_plural': 'historical Regions'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'permissions': [('custom_create_region', 'Can Create Region'), ('custom_delete_region', 'Can Delete Region'), ('custom_update_region', 'Can Update Region'), ('custom_view_region', 'Can View Region')], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelTable(
            name='district',
            table='District',
        ),
        migrations.AlterModelTable(
            name='grade',
            table='Rank',
        ),
        migrations.AlterModelTable(
            name='region',
            table='Region',
        ),
    ]
