# Generated by Django 4.1.10 on 2023-07-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_district_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicalgrade',
            old_name='grade_name',
            new_name='name',
        ),
    ]
