# Generated by Django 4.1.10 on 2023-07-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_historicaluser_group_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
