# Generated by Django 4.1.10 on 2023-07-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_historicaluser_status_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='staffid',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staffid',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
