# Generated by Django 4.1.10 on 2023-07-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_historicaluser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
