# Generated by Django 4.1.10 on 2023-07-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_user_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
