# Generated by Django 4.1.10 on 2023-07-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('authentication', '0021_delete_historicaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldistrict',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldistrict',
            name='region',
        ),
        migrations.RemoveField(
            model_name='historicalregion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.AddField(
            model_name='grade',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='company.tenants'),
        ),
        migrations.AddField(
            model_name='historicalgrade',
            name='tenant_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.tenants'),
        ),
        migrations.AddField(
            model_name='user',
            name='devision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devisions', to='company.devision'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_districts', to='company.sub_devision'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.tenants'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='HistoricalDistrict',
        ),
        migrations.DeleteModel(
            name='HistoricalRegion',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
