# Generated by Django 4.1.10 on 2023-08-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_historicaldistrict_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('custom_create_user', 'Can Create User'), ('custom_delete_user', 'Can Delete User'), ('custom_update_user', 'Can Update User'), ('custom_view_user', 'Can View User'), ('custom_view_report', 'Can View Reports')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
