# Generated by Django 4.1.10 on 2023-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hq',
            field=models.BooleanField(default=False),
        ),
    ]
