# Generated by Django 4.1.10 on 2023-08-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
