# Generated by Django 4.1.10 on 2023-08-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_tenants_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='devision',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sub_devision',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
