# Generated by Django 4.1.10 on 2023-11-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_devision_code_sub_devision_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_devision',
            name='tag',
            field=models.BooleanField(default=False),
        ),
    ]
