# Generated by Django 4.1.6 on 2024-03-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixedassets', '0024_fixedasset_costbf_fixedasset_costcf_and_more'),
        ('company', '0006_sub_devision_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='devision',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devisionlocation', to='fixedassets.location'),
        ),
        migrations.AlterField(
            model_name='sub_devision',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdevisionlocation', to='fixedassets.location'),
        ),
    ]
