# Generated by Django 4.1.6 on 2024-03-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_devision_location_alter_sub_devision_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devision',
            name='location',
        ),
    ]
