# Generated by Django 4.1.10 on 2023-08-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_approvals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('start', models.CharField(blank=True, max_length=250, null=True)),
                ('end', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'AccountClass',
                'verbose_name_plural': 'AccountClass',
                'db_table': 'AccountClass',
                'permissions': [('custom_create_chart_of_accounts', 'Can Create Chart of Accounts'), ('custom_update_chart_of_accounts', 'Can Update Chart of Accounts'), ('custom_delete_chart_of_accounts', 'Can Delete Chart of Accounts'), ('custom_view_chart_of_accounts', 'Can View Chart of Accounts')],
            },
        ),
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('start', models.CharField(blank=True, max_length=250, null=True)),
                ('end', models.CharField(blank=True, max_length=250, null=True)),
                ('account_class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountclass', to='accounting.account_class')),
            ],
            options={
                'verbose_name': 'AccountItem',
                'verbose_name_plural': 'AccountItems',
                'db_table': 'AccountItem',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('symbol', models.CharField(blank=True, max_length=250, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencys',
                'db_table': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='Fiscal_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=250)),
                ('start', models.CharField(max_length=250)),
                ('end', models.CharField(max_length=250)),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_year', to='company.tenants')),
            ],
            options={
                'verbose_name': 'Fiscal_Year',
                'verbose_name_plural': 'Fiscal_Years',
                'db_table': 'Fiscal_Year',
            },
        ),
        migrations.CreateModel(
            name='AccountSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('start', models.CharField(blank=True, max_length=250, null=True)),
                ('end', models.CharField(blank=True, max_length=250, null=True)),
                ('account_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountitem', to='accounting.accountitem')),
            ],
            options={
                'verbose_name': 'AccountSubItem',
                'verbose_name_plural': 'AccountSubItems',
                'db_table': 'AccountSubItem',
            },
        ),
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('account_sub_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountsubitem', to='accounting.accountsubitem')),
            ],
            options={
                'verbose_name': 'AccountLedger',
                'verbose_name_plural': 'AccountLedgers',
                'db_table': 'AccountLedger',
            },
        ),
    ]
