# Generated by Django 4.1.10 on 2023-08-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_tenants_code'),
        ('accounting', '0002_alter_currency_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.tenants')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Devisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devision', to='accounting.departments')),
            ],
            options={
                'verbose_name': 'Devisions',
                'verbose_name_plural': 'Devisions',
                'db_table': 'Devisions',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='accounting.devisions')),
            ],
            options={
                'verbose_name': 'Units',
                'verbose_name_plural': 'Units',
                'db_table': 'Units',
            },
        ),
    ]
