# Generated by Django 4.1.10 on 2023-08-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_departments_devisions_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='unit',
            new_name='devision',
        ),
    ]
