# Generated by Django 4.1.10 on 2023-08-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_devisions_department_remove_units_devision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_class',
            name='end',
        ),
        migrations.RemoveField(
            model_name='account_class',
            name='start',
        ),
    ]
