# Generated by Django 4.1.10 on 2023-08-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_account_class_end_remove_account_class_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountitem',
            name='maincode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
