# Generated by Django 4.1.10 on 2023-08-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountitem_maincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountitem',
            name='end',
        ),
        migrations.RemoveField(
            model_name='accountitem',
            name='start',
        ),
    ]
