# Generated by Django 4.1.10 on 2023-09-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_accountitem_end_remove_accountitem_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountitem',
            name='maincode',
        ),
    ]
