# Generated by Django 4.1.10 on 2023-09-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_devision_code_sub_devision_code'),
        ('accounting', '0009_remove_accountitem_maincode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscal_year',
            options={'permissions': [('custom_create_fisical_year', 'Can Create Fiscal Year')], 'verbose_name': 'Fiscal_Year', 'verbose_name_plural': 'Fiscal_Years'},
        ),
        migrations.AddField(
            model_name='fiscal_year',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fiscal_year',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Open', 'Open'), ('In Active', 'In Active')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fiscal_year',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscalaccounting_year', to='company.tenants'),
        ),
    ]
