# Generated by Django 4.1.10 on 2023-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_fiscal_year_options_fiscal_year_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal_year',
            name='end',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fiscal_year',
            name='period',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fiscal_year',
            name='start',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
