# Generated by Django 4.1.10 on 2023-09-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_fiscal_year_end_alter_fiscal_year_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal_year',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscal_year',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
