# Generated by Django 4.1.10 on 2023-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_fiscal_year_end_alter_fiscal_year_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Activate', 'In Activate')], default='In Activate', max_length=50),
        ),
    ]
