# Generated by Django 4.1.10 on 2023-09-25 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_devision_code_sub_devision_code'),
        ('dms', '0036_document_reverse'),
        ('accounting', '0014_alter_accountledger_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'BankAccountsType',
                'verbose_name_plural': 'BankAccountsTypes',
                'db_table': 'BankAccountsTypes',
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('pv_date', models.DateField(blank=True, null=True)),
                ('type_of_pay', models.CharField(choices=[('Third Party', 'Third Party'), ('Regional', 'Regional'), ('District', 'District'), ('Staff', 'Staff')], default='Staff', max_length=100)),
                ('type_of_pv', models.CharField(choices=[('GIFMIS', 'GIFMIS'), ('Internal', 'Internal')], default='Internal', max_length=100)),
                ('withholding_tax', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100)),
                ('payto', models.CharField(blank=True, max_length=250, null=True)),
                ('pay_to_address', models.CharField(blank=True, max_length=250, null=True)),
                ('warrant_no', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Authorised', 'Authorised'), ('Authorised & Passed', 'Authorised & Passed'), ('Paid', 'Paid')], default='Staff', max_length=100)),
                ('prepared_by_date', models.DateField(blank=True, null=True)),
                ('authorized_by_date', models.DateField(blank=True, null=True)),
                ('authorized_and_passed_by_date', models.DateField(blank=True, null=True)),
                ('paid_by_date', models.DateField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_number_date', models.DateField(blank=True, null=True)),
                ('authorized_and_passed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizedpassedby', to=settings.AUTH_USER_MODEL)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizedby', to=settings.AUTH_USER_MODEL)),
                ('bankaccounttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvdbat', to='accounting.bankaccountstype')),
                ('devision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvdevisions', to='company.devision')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvdocument', to='dms.document')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paidby', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparedby', to=settings.AUTH_USER_MODEL)),
                ('sub_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvsub_districts', to='company.sub_devision')),
            ],
            options={
                'verbose_name': 'PaymentVoucher',
                'verbose_name_plural': 'PaymentVoucher',
                'db_table': 'PaymentVoucher',
                'permissions': [('custom_create_pv', 'Can Create PV'), ('custom_update_pv', 'Can Update PV'), ('custom_delete_pv', 'Can Delete PV '), ('custom_view_pv', 'Can View PV '), ('custom_approve_pv', 'Can Approve PV '), ('custom_authorise_pv', 'Can Authorise PV '), ('custom_authorise_annd_pass_pv', 'Can Authorise and pass PV '), ('custom_pay_pv', 'Can Pay PV'), ('custom_add_cheque_no', 'Can Add Cheque No'), ('custom_pay_impress', 'Can Pay Impress')],
            },
        ),
        migrations.AddField(
            model_name='accountledger',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Pvtimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.CharField(blank=True, max_length=255, null=True)),
                ('timeline_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('timelinedate', models.DateTimeField(auto_now_add=True)),
                ('pv_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvtimeline', to='accounting.paymentvoucher')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pvtimeline',
                'verbose_name_plural': 'Pvtimelines',
                'db_table': 'Pvtimelines',
            },
        ),
        migrations.CreateModel(
            name='PvDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('accout_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubitem', to='accounting.accountledger')),
            ],
            options={
                'verbose_name': 'PvDetail',
                'verbose_name_plural': 'PvDetails',
                'db_table': 'PvDetails',
            },
        ),
        migrations.CreateModel(
            name='Imprest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impress_date', models.DateField(blank=True, null=True)),
                ('claim_detail', models.CharField(blank=True, max_length=700, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('ammount_given', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('actual_expense', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedby', to=settings.AUTH_USER_MODEL)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorisedby', to=settings.AUTH_USER_MODEL)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifiedby', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raisedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imprest',
                'verbose_name_plural': 'Imprests',
                'db_table': 'Imprests',
            },
        ),
    ]
