# Generated by Django 4.1.10 on 2023-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_alter_paymentvoucher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Authorised', 'Authorised'), ('Authorised & Passed', 'Authorised & Passed'), ('Pv Eligibility', 'Pv Eligibility'), ('Paid', 'Paid')], default='Staff', max_length=100),
        ),
    ]
