# Generated by Django 4.1.10 on 2023-09-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_alter_paymentvoucher_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentvoucher',
            options={'permissions': [('custom_create_pv', 'Can Create PV'), ('custom_update_pv', 'Can Update PV'), ('custom_delete_pv', 'Can Delete PV '), ('custom_view_pv', 'Can View PV'), ('custom_approve_pv', 'Can Approve PV'), ('custom_authorise_pv', 'Can Authorise PV '), ('custom_authorise_annd_pass_pv', 'Can Authorise and pass PV '), ('custom_pay_pv', 'Can Pay PV'), ('custom_add_cheque_no', 'Can Add Cheque No'), ('custom_pay_impress', 'Can Pay Impress'), ('custom_headoffice', 'Is in Head Office')], 'verbose_name': 'PaymentVoucher', 'verbose_name_plural': 'PaymentVoucher'},
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Authorised', 'Authorised'), ('Authorised & Passed', 'Authorised & Passed'), ('Check No Entered', 'Check No Entered'), ('Pv Eligibility', 'Pv Eligibility'), ('Paid', 'Paid')], default='Staff', max_length=100),
        ),
    ]
