# Generated by Django 4.1.10 on 2023-09-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_paymentvoucher_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='authorized_and_passed_by',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='authorized_and_passed_by_date',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='authorized_by_date',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='paid_by_date',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='prepared_by_date',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
