# Generated by Django 4.1.10 on 2023-09-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_remove_paymentvoucher_authorized_and_passed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='type_of_pay',
            field=models.CharField(choices=[('Third Party', 'Third Party'), ('Refund', 'Refund'), ('Accountable Imprest', 'Accountable Imprest')], default='Accountable Imprest', max_length=100),
        ),
    ]
