# Generated by Django 4.1.10 on 2023-09-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_paymentvoucher_type_of_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pvdetail',
            name='pv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='accounting.paymentvoucher'),
        ),
    ]
