# Generated by Django 4.1.10 on 2023-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_paymentvoucher_withholding_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
