# Generated by Django 4.1.10 on 2023-10-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_paymentvoucher_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='acoounting_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvyr', to='accounting.fiscal_year'),
        ),
    ]
