# Generated by Django 4.1.10 on 2023-10-05 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0027_paymentvoucher_acoounting_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentvoucher',
            options={'permissions': [('custom_create_pv', 'Can Create PV'), ('custom_update_pv', 'Can Update PV'), ('custom_delete_pv', 'Can Delete PV '), ('custom_view_pv', 'Can View PV'), ('custom_approve_pv', 'Can Approve PV'), ('custom_authorise_pv', 'Can Authorise PV '), ('custom_authorise_annd_pass_pv', 'Can Authorise and pass PV '), ('custom_pay_pv', 'Can Pay PV'), ('custom_add_cheque_no', 'Can Add Cheque No'), ('custom_pay_impress', 'Can Pay Impress'), ('custom_headoffice', 'Is in Head Office'), ('custom_regional', 'Is in Regional Office')], 'verbose_name': 'PaymentVoucher', 'verbose_name_plural': 'PaymentVoucher'},
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
