# Generated by Django 4.1.10 on 2023-10-05 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0039_document_sub_division'),
        ('accounting', '0031_pveligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='document_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvdocumentdestination', to='dms.documentdestination'),
        ),
    ]
