# Generated by Django 4.1.10 on 2023-10-09 12:53

from django.db import migrations, models
import django.db.models.deletion
import dms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_devision_code_sub_devision_code'),
        ('accounting', '0032_paymentvoucher_document_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='mode_of_pv',
            field=models.CharField(choices=[('GIFMIS', 'GIFMIS'), ('Internal', 'Internal')], default='Internal', max_length=100),
        ),
        migrations.AddField(
            model_name='pveligibility',
            name='accout_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insubitem', to='accounting.accountledger'),
        ),
        migrations.AddField(
            model_name='pveligibility',
            name='cost_center',
            field=models.CharField(choices=[('Cost Center 1', 'Cost Center 1'), ('Cost Center 2', 'Cost Center 2'), ('Cost Center 3', 'Cost Center 3'), ('Cost Center 4', 'Cost Center 4'), ('Cost Center 5', 'Cost Center 5')], default='Cost Center 1', max_length=50),
        ),
        migrations.AddField(
            model_name='pveligibility',
            name='return_to_chest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pveligibility',
            name='return_to_chest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pveligibility',
            name='source_of_funding',
            field=models.CharField(choices=[('GOG', 'GOG'), ('Others', 'Others')], default='GOG', max_length=50),
        ),
        migrations.AddField(
            model_name='pveligibility',
            name='type_of_pv',
            field=models.CharField(choices=[('General', 'General'), ('Honorarium', 'Honorarium')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='type_of_pv',
            field=models.CharField(choices=[('General', 'General'), ('Honorarium', 'Honorarium')], default='General', max_length=100),
        ),
        migrations.CreateModel(
            name='SubDevisionAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankaccounttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dbat', to='accounting.bankaccountstype')),
                ('sub_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datsub_districts', to='company.sub_devision')),
            ],
        ),
        migrations.CreateModel(
            name='Paymentattachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(upload_to='pvdocuments/%Y/%m/%d/', validators=[dms.validators.validate_file_extension])),
                ('pv_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvattachment', to='accounting.paymentvoucher')),
            ],
            options={
                'verbose_name': 'Pvattachement',
                'verbose_name_plural': 'Pvattachement',
                'db_table': ' Pvattachements',
            },
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='bankaccounttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvdbat', to='accounting.subdevisionaccounttype'),
        ),
    ]
