# Generated by Django 4.1.10 on 2023-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_paymentvoucher_mode_of_pv_pveligibility_accout_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pveligibility',
            name='status',
            field=models.CharField(choices=[('---------', '---------'), ('Completed', 'Completed'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='---------', max_length=60),
        ),
    ]
