# Generated by Django 4.1.10 on 2023-10-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_pveligibility_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdevisionaccounttype',
            options={'verbose_name': 'SubDevisionAccountType', 'verbose_name_plural': 'SubDevisionAccountType'},
        ),
        migrations.AlterModelTable(
            name='subdevisionaccounttype',
            table='SubDevisionAccountType',
        ),
    ]
