# Generated by Django 4.1.10 on 2023-10-09 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_alter_subdevisionaccounttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pveligibility',
            name='bankaccounttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iadbat', to='accounting.subdevisionaccounttype'),
        ),
        migrations.AddField(
            model_name='pveligibility',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
