# Generated by Django 4.1.10 on 2023-10-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_devision_code_sub_devision_code'),
        ('accounting', '0038_alter_pveligibility_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprest',
            name='acoounting_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imyr', to='accounting.fiscal_year'),
        ),
        migrations.CreateModel(
            name='Payables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Awaiting Payment', 'Awaiting Payment'), ('Recipient Notified', 'Recipient Notified'), ('Amount Paid', 'Amount Paid')], default='Awaiting Payment', max_length=60)),
                ('acoounting_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apyr', to='accounting.fiscal_year')),
                ('devision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apdevisions', to='company.devision')),
                ('pv_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvap', to='accounting.paymentvoucher')),
                ('sub_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apsub_districts', to='company.sub_devision')),
            ],
        ),
    ]
