# Generated by Django 4.1.10 on 2023-10-11 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_imprest_acoounting_year_payables'),
    ]

    operations = [
        migrations.AddField(
            model_name='payables',
            name='apdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
