# Generated by Django 4.1.10 on 2023-10-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_paymentvoucherbeneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucherbeneficiary',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
