# Generated by Django 4.1.10 on 2023-10-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_paymentvoucherbeneficiary_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucherbeneficiary',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
