# Generated by Django 4.1.10 on 2023-10-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_alter_paymentvoucherbeneficiary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucherbeneficiary',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
