# Generated by Django 4.1.10 on 2023-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_alter_payables_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Certified', 'Certified')], default='Pending', max_length=60),
        ),
    ]
