# Generated by Django 4.1.10 on 2023-10-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_imprest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imprest',
            options={'permissions': [('custom_create_imprest', 'Can Create Imprest'), ('custom_approve_imprest', 'Can Approve Imprest'), ('custom_certify_imprest', 'Can Certify Imprest'), ('custom_pay_imprest', 'Can Pay Imprest')], 'verbose_name': 'Imprest', 'verbose_name_plural': 'Imprests'},
        ),
    ]
