# Generated by Django 4.1.10 on 2023-10-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_alter_imprest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprest',
            name='approved_rank',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='imprest',
            name='approved_sub_division',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='imprest',
            name='certified_rank',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='imprest',
            name='certified_sub_division',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='imprest',
            name='raised_rank',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='imprest',
            name='raised_sub_division',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
