# Generated by Django 4.1.10 on 2023-11-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_imprest_paid_by_imprest_paid_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprest',
            name='notifyhod',
            field=models.BooleanField(default=False),
        ),
    ]
