# Generated by Django 4.1.10 on 2023-11-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_imprest_notifyhod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprest',
            name='actual_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='imprest',
            name='ammount_given',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='imprest',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
