# Generated by Django 4.1.6 on 2024-05-17 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_alter_imprest_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucherbeneficiary',
            name='staff',
        ),
        migrations.AddField(
            model_name='paymentvoucherbeneficiary',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucherbeneficiary',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must begin with 0 and contain only 10 digits', regex='^(0)\\d{9}$')]),
        ),
    ]
