# Generated by Django 4.1.6 on 2024-05-17 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_remove_paymentvoucherbeneficiary_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number_date', models.DateField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Posted', 'Posted'), ('Pending', 'Pending')], default='Pending', max_length=100)),
                ('pv_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvchirld', to='accounting.paymentvoucher')),
            ],
            options={
                'verbose_name': 'PvPayment',
                'verbose_name_plural': 'PvPayments',
                'db_table': 'PvPayments',
            },
        ),
    ]
