# Generated by Django 4.1.6 on 2024-05-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0061_pvpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpayment',
            name='pv_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
