# Generated by Django 4.1.6 on 2024-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0062_pvpayment_pv_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='pv_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='pv_amount_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='pv_amount_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
