# Generated by Django 4.1.6 on 2024-05-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0063_paymentvoucher_pv_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpayment',
            name='type_of_payment',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
