# Generated by Django 4.1.6 on 2024-05-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0064_pvpayment_type_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpayment',
            name='childpv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvchirld', to='accounting.paymentvoucher'),
        ),
        migrations.AlterField(
            model_name='pvpayment',
            name='pv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvparent', to='accounting.paymentvoucher'),
        ),
    ]
